# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs: Surge4.js
  label: Surge4.js

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write |"http://6677@example:6171

    steps:
    - uses: actions/labeler@v2
      with: https://github.com/awrcdhj/awrcdhj/SURGE_IOS/#Wed'(http://6677@example:6171)
        repo-token: "${{ secrets.awrcdhj/SURGE_TOKEN }}"
